name: hello github actions

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello from an inline bash script in a GitHub Action Workflow!"
  hello-from-javascript:
    runs-on: ubuntu-24
    steps:
      - run: const message = "Hello from an inline JavaScript script in a GitHub Action Workflow!"; console.log(message);
        shell: node
  hello-from-python:
    runs-on: ubuntu-24
    steps:
      - run: print("Hello from an inline python script in a GitHub Action Workflow!")
        shell: python
